name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9' 

      - name: Install dependencies
        run: |
# pip install Flask gunicorn requests mock flask_wtf coverage python-dotenv
          sudo apt-get update
          sudo apt-get install -y libssl-dev libffi-dev python3-dev
          pip install -r src/requirements.txt

      - name: Run tests and coverage
        run: |
         coverage run src/tests/main_test.py
         coverage run src/tests/email_test.py
         coverage run src/tests/cobranca_test.py
         coverage xml -o coverage.xml
        continue-on-error: true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
