name: Deploy to Cloud Run

on:
 push:
  #tags:
    branches:
      #- v*
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2
      with:
        project_id: microservice-externo
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Update Google Cloud SDK
      run: gcloud components update

    - name: Configure Docker authentication for Google Container Registry
      run: gcloud auth configure-docker

    - name: Build and Push Docker image
      run: |
        docker buildx build --platform linux/amd64 -t gcr.io/microservice-externo/microservice-externo:$GITHUB_SHA src/
        docker push gcr.io/microservice-externo/microservice-externo:$GITHUB_SHA
        
    - name: Save Secrets to GCP Secret Manager
      env: 
       GCP_PROJECT_ID: microservice-externo
       GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: |
        gcloud secrets create MAIL_USERNAME --data-file <(echo -n ${{secrets.MAIL_USERNAME}})
        gcloud secrets create MAIL_PASSWORD --data-file <(echo -n ${{secrets.MAIL_PASSWORD}})
        gcloud secrets create STRIPE_PRIVATE_KEY --data-file <(echo -n ${{ secrets.STRIPE_PRIVATE_KEY }})
        
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy microservice-externo \
          --image gcr.io/microservice-externo/microservice-externo:$GITHUB_SHA \
          --platform managed \
          --region us-central1
      env:
         MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
         MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
         STRIPE_PRIVATE_KEY: ${{ secrets.STRIPE_PRIVATE_KEY }}
